import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import inlineImportPlugin from 'esbuild-plugin-inline-import';
import fs from 'node:fs'


const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: "inline",
    metafile: true,
	treeShaking: true,
	outfile: "build/main.js",
	platform: "browser",
	plugins: [
		inlineImportPlugin()
	],
});

const result = await context.rebuild();
fs.writeFileSync('build/meta.json', JSON.stringify(result.metafile))
process.exit(0);
